version: '3'
services:
 # Nginx server configuration   
  web:
    image: nginx:1.17
    depends_on:
      - mysql
      - php
    links:
      - mysql
      - php
    volumes:
      - ./:/var/www/html
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - "8080:80"
 # Php-fpm configuration
  php:
    build: ./php
    volumes:
      - ./:/var/www/html
 # Mysql configuration
  mysql:
    image: mysql:5.7
    restart: always
    environment:
        - MYSQL_DATABASE=weather
        - MYSQL_ROOT_PASSWORD=root123
        - MYSQL_USER=weather
        - MYSQL_PASSWORD=root
    ports:
        - "3306:3306"
    volumes:
        - ./mysql:/docker-entrypoint-initdb.d:ro